In [52]:
import numpy as np


In [53]:
L=[1,2,3]
A=np.array([1,2,3])


In [54]:
for e in L:
    print(e)

1
2
3


In [55]:
for e in A:
    print(e)

1
2
3


In [56]:
L.append(4)

In [57]:
L+[5]

[1, 2, 3, 4, 5]

In [58]:
 A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
A+np.array([4])

In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

result = a + b
print(result)


[[11 22 33]
 [14 25 36]]


In [ ]:
A+np.array([1,2,3])

In [66]:
((A+np.array([1,2,3]))*2)*2


array([ 8, 16, 24])

In [ ]:
L

In [ ]:
L2=[e+3 for e in L]
L2

In [68]:
A**2

array([1, 4, 9])

In [67]:
L3=[]
for e in L:
    L3.append(e**2)
L3

[1, 4, 9, 16]

In [ ]:
A

In [ ]:
np.sqrt(A)

In [ ]:
 np.exp(A)

In [60]:
an=np.array([4,5])
bn=np.array([6,3])


In [61]:
dot = 0
for e,f in zip(an,bn):
    dot+=e*f
dot

39

In [62]:
an*bn

array([24, 15])

In [64]:
 np.sum(an*bn)

39